In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("iris.csv",header=None,sep=',')

In [3]:
df.head()

0                  1                   2  \
0  sepal length in cm  sepal width in cm  petal length in cm   
1                 5.1                3.5                 1.4   
2                 4.9                3.0                 1.4   
3                 4.7                3.2                 1.3   
4                 4.6                3.1                 1.5   

                   3            4  
0  petal width in cm        class  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

In [4]:
df.dropna(how="all",inplace=True)

In [5]:
df.tail()

0    1    2    3               4
146  6.7  3.0  5.2  2.3  Iris-virginica
147  6.3  2.5  5.0  1.9  Iris-virginica
148  6.5  3.0  5.2  2.0  Iris-virginica
149  6.2  3.4  5.4  2.3  Iris-virginica
150  5.9  3.0  5.1  1.8  Iris-virginica

In [25]:
X = df.loc[1:,0:3].values
y = df.loc[:,4].values

In [26]:
X


array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [16]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [27]:
X_std = scaler.fit_transform(X)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [28]:
X_std

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [30]:
df.convert_objects(convert_numeric=True)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


0    1    2    3               4
0    NaN  NaN  NaN  NaN           class
1    5.1  3.5  1.4  0.2     Iris-setosa
2    4.9  3.0  1.4  0.2     Iris-setosa
3    4.7  3.2  1.3  0.2     Iris-setosa
4    4.6  3.1  1.5  0.2     Iris-setosa
5    5.0  3.6  1.4  0.2     Iris-setosa
6    5.4  3.9  1.7  0.4     Iris-setosa
7    4.6  3.4  1.4  0.3     Iris-setosa
8    5.0  3.4  1.5  0.2     Iris-setosa
9    4.4  2.9  1.4  0.2     Iris-setosa
10   4.9  3.1  1.5  0.1     Iris-setosa
11   5.4  3.7  1.5  0.2     Iris-setosa
12   4.8  3.4  1.6  0.2     Iris-setosa
13   4.8  3.0  1.4  0.1     Iris-setosa
14   4.3  3.0  1.1  0.1     Iris-setosa
15   5.8  4.0  1.2  0.2     Iris-setosa
16   5.7  4.4  1.5  0.4     Iris-setosa
17   5.4  3.9  1.3  0.4     Iris-setosa
18   5.1  3.5  1.4  0.3     Iris-setosa
19   5.7  3.8  1.7  0.3     Iris-setosa
20   5.1  3.8  1.5  0.3     Iris-setosa
21   5.4  3.4  1.7  0.2     Iris-setosa
22   5.1  3.7  1.5  0.4     Iris-setosa
23   4.6  3.6  1.0  0.2     Iris-setosa
24   5.1  3.3  1.7  0.5     Iris-setosa
25   4.8  3.4  1.9  0.2     Iris-setosa
26   5.0  3.0  1.6  0.2     Iris-setosa
27   5.0  3.4  1.6  0.4     Iris-setosa
28   5.2  3.5  1.5  0.2     Iris-setosa
29   5.2  3.4  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
121  6.9  3.2  5.7  2.3  Iris-virginica
122  5.6  2.8  4.9  2.0  Iris-virginica
123  7.7  2.8  6.7  2.0  Iris-virginica
124  6.3  2.7  4.9  1.8  Iris-virginica
125  6.7  3.3  5.7  2.1  Iris-virginica
126  7.2  3.2  6.0  1.8  Iris-virginica
127  6.2  2.8  4.8  1.8  Iris-virginica
128  6.1  3.0  4.9  1.8  Iris-virginica
129  6.4  2.8  5.6  2.1  Iris-virginica
130  7.2  3.0  5.8  1.6  Iris-virginica
131  7.4  2.8  6.1  1.9  Iris-virginica
132  7.9  3.8  6.4  2.0  Iris-virginica
133  6.4  2.8  5.6  2.2  Iris-virginica
134  6.3  2.8  5.1  1.5  Iris-virginica
135  6.1  2.6  5.6  1.4  Iris-virginica
136  7.7  3.0  6.1  2.3  Iris-virginica
137  6.3  3.4  5.6  2.4  Iris-virginica
138  6.4  3.1  5.5  1.8  Iris-virginica
139  6.0  3.0  4.8  1.8  Iris-virginica
140  6.9  3.1  5.4  2.1  Iris-virginica
141  6.7  3.1  5.6  2.4  Iris-virginica
142  6.9  3.1  5.1  2.3  Iris-virginica
143  5.8  2.7  5.1  1.9  Iris-virginica
144  6.8  3.2  5.9  2.3  Iris-virginica
145  6.7  3.3  5.7  2.5  Iris-virginica
146  6.7  3.0  5.2  2.3  Iris-virginica
147  6.3  2.5  5.0  1.9  Iris-virginica
148  6.5  3.0  5.2  2.0  Iris-virginica
149  6.2  3.4  5.4  2.3  Iris-virginica
150  5.9  3.0  5.1  1.8  Iris-virginica

[151 rows x 5 columns]

In [32]:
df.drop(0,inplace=True)

In [47]:
X = df.loc[:,0:3]
X

0    1    2    3
1    5.1  3.5  1.4  0.2
2    4.9  3.0  1.4  0.2
3    4.7  3.2  1.3  0.2
4    4.6  3.1  1.5  0.2
5    5.0  3.6  1.4  0.2
6    5.4  3.9  1.7  0.4
7    4.6  3.4  1.4  0.3
8    5.0  3.4  1.5  0.2
9    4.4  2.9  1.4  0.2
10   4.9  3.1  1.5  0.1
11   5.4  3.7  1.5  0.2
12   4.8  3.4  1.6  0.2
13   4.8  3.0  1.4  0.1
14   4.3  3.0  1.1  0.1
15   5.8  4.0  1.2  0.2
16   5.7  4.4  1.5  0.4
17   5.4  3.9  1.3  0.4
18   5.1  3.5  1.4  0.3
19   5.7  3.8  1.7  0.3
20   5.1  3.8  1.5  0.3
21   5.4  3.4  1.7  0.2
22   5.1  3.7  1.5  0.4
23   4.6  3.6  1.0  0.2
24   5.1  3.3  1.7  0.5
25   4.8  3.4  1.9  0.2
26   5.0  3.0  1.6  0.2
27   5.0  3.4  1.6  0.4
28   5.2  3.5  1.5  0.2
29   5.2  3.4  1.4  0.2
30   4.7  3.2  1.6  0.2
..   ...  ...  ...  ...
121  6.9  3.2  5.7  2.3
122  5.6  2.8  4.9  2.0
123  7.7  2.8  6.7  2.0
124  6.3  2.7  4.9  1.8
125  6.7  3.3  5.7  2.1
126  7.2  3.2  6.0  1.8
127  6.2  2.8  4.8  1.8
128  6.1  3.0  4.9  1.8
129  6.4  2.8  5.6  2.1
130  7.2  3.0  5.8  1.6
131  7.4  2.8  6.1  1.9
132  7.9  3.8  6.4  2.0
133  6.4  2.8  5.6  2.2
134  6.3  2.8  5.1  1.5
135  6.1  2.6  5.6  1.4
136  7.7  3.0  6.1  2.3
137  6.3  3.4  5.6  2.4
138  6.4  3.1  5.5  1.8
139  6.0  3.0  4.8  1.8
140  6.9  3.1  5.4  2.1
141  6.7  3.1  5.6  2.4
142  6.9  3.1  5.1  2.3
143  5.8  2.7  5.1  1.9
144  6.8  3.2  5.9  2.3
145  6.7  3.3  5.7  2.5
146  6.7  3.0  5.2  2.3
147  6.3  2.5  5.0  1.9
148  6.5  3.0  5.2  2.0
149  6.2  3.4  5.4  2.3
150  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [45]:
d = np.mean(X_std,axis=0)

In [69]:
x = X.values
X.shape

(150, 4)

In [71]:
x = x.astype(np.float)

In [72]:
x.reshape(150,4)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [74]:
np.mean(x,axis=0)

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [76]:
np.std(x,axis=0)

array([0.82530129, 0.43214658, 1.75852918, 0.76061262])

In [77]:
X_std

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [78]:
cor = np.cov(X_std.T)

In [79]:
cor

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [81]:
eig_val, eig_vec = np.linalg.eig(cor)

In [82]:
eig_val

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

In [ ]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]


eig_pairs.sort(key=lambda x: x[0], reverse=True)